### ISSUE TITLE
如何配置指定名称的组件才在components.d.ts文件中生成类型声明

### ISSUE THREAD

**Issue by JackieCheung** [unplugin/unplugin-vue-components#420]
例如，有如下组件目录结构：
```
--component-a
----child-a.vue
----child-b.vue
----index.vue
```
这样`index.vue`、`child-a.vue`、`child-b.vue`都会生成类型声明，但实际上`child-a`和`child-b`组件作为`component-a`组件的子组件，并不需要单独对外暴露的，而且`child-a.vue`、`child-b.vue`还有可能与其它组件重名，有没有办法只匹配到名字为`index`的组件才生成类型声明，尝试了`include`属性，好像没效果

**Comment by azaleta** [comment]
@JackieCheung 

currently you can't do this
[Glob Scan](https://github.com/antfu/unplugin-vue-components/blob/main/src/core/fs/glob.ts)
does not filter files by include/exclude (they are settings for transform)

**Comment by kingyue737** [comment]
I also want this feature because I don't want type declarations provided by Vue2 UI library (all the component types are `any`), I define the types of these components myself. While I still want `unplugin-vue-components` to generate other components' type for me.

**Comment by paul-xia** [comment]
I also want this feature too.

**Comment by cx741041875** [comment]
您好，请问有解决办法了吗？我也有这个困惑

**Comment by wen403** [comment]
@lishaobos 大佬你这个pr怎么使用啊

**Comment by lishaobos** [comment]
就是和 glob 规则一样，你最开始加个 ! , 例如：!src/xx.vue

**Comment by wen403** [comment]
@lishaobos 
![image](https://github.com/antfu/unplugin-vue-components/assets/67454874/b195d797-0768-48b5-8656-39fcaeb15b1c)
你有遇到这种情况嘛，我的插件是最新的，也重启重装过依赖

**Comment by lishaobos** [comment]
这个 globs 里面可以写多个，你写了一个排除，可以再写几个命中，类似于下面

```
      globs: [
        'src/components/*.vue',
        '!src/components/ComponentA.vue',
      ],
```

**Comment by AprilLemon** [comment]
globs: [
    // '!src/components/**/modules/*.vue',
    'src/components/*.vue',
    'src/components/**/index.vue',
  ],
用这种方式

**Comment by AprilLemon** [comment]
globs: [
    // '!src/components/**/modules/*.vue',
    'src/components/*.vue',
    'src/components/**/index.vue',
  ],

使用这种方式来排除
