### ISSUE TITLE
Excluded components still have warnings like "xxx has naming conflicts with other components, ignored"

### ISSUE THREAD

**Issue by wxfred** [unplugin/unplugin-vue-components#617]
### Describe the bug

I'm using vue3, and config unplugin-vue-compoents as below
```
module.exports = defineConfig({
  configureWebpack: {
    plugins: [
      Components({
        exclude: [/[\\/]nodes[\\/]/],
      }),
    ]
  },
```

But **npm run serve** still has those warning or somethings
`[unplugin-vue-components] component "SourceNode"(x:/xxxx/src/components/nodes/SourceNode.vue) has naming conflicts with other components, ignored.`

### Reproduction

create two components with the same name, one under the components folder, one under the components/nodes folder, then config this plugin with exclude: [/[\\/]nodes[\\/]/]

### System Info

```Shell
vue: 3.2.47
unplugin-vue-components: 0.22.12
@vue/cli: 5.0.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by io-o** [comment]
you can set 
```
directoryAsNamespace: true
```
