### ISSUE TITLE
为什么将node_modules里面的未编译的vue文件加入AntDesignVueResolver后无效

### ISSUE THREAD

**Issue by lllianreg** [unplugin/unplugin-vue-components#654]
### Describe the bug

```
// private-component-library/demo.vue
<a-tabs v-model:activeKey="tabKey">
// TODO
</a-tabs>

// vite.config.js
Components({
    resolvers: [AntDesignVueResolver({
      exclude: ['AModal']
    })],
    include: [/[\\/]node_modules[\\/]private-component-library/, /\.vue$/, /\.vue\?vue/]
 }),
```
结果
![Snipaste_2023-07-07_11-43-15](https://github.com/antfu/unplugin-vue-components/assets/21689406/e6b1b782-2508-4109-b92b-2dd69845ac3f)

### Reproduction

[test](https://codesandbox.io/p/sandbox/headless-hooks-7755zn)

### System Info

```Shell
win32
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lllianreg** [comment]
解决了
```
exclude: [/[\\/]node_modules[\\/]((?!private-component-library|private-component-library-vite\/).)/, /[\\/]\.git[\\/]/, /[\\/]\.nuxt[\\/]/]
```
另外 如果引入了cdn 需要 externals
```
import { viteExternalsPlugin } from 'vite-plugin-externals'
plugins.viteExternalsPlugin((isPro ? {
  vue: 'Vue',
} : {}),)
```

**Comment by vivid05** [comment]
> vite-plugin-externals

跟vite-plugin-cdn-import这个插件一起用会有冲突，有解决方案不
