### ISSUE TITLE
Proposal regarding the component

### ISSUE THREAD

**Issue by voyageh** [unplugin/unplugin-vue-components#694]
### Clear and concise description of the problem

```vue
<template>
  <component :is="ElInput"/>
</template>

<script setup lang="ts">
import { resolveComponent as _resolveComponent } from "vue";
const ElInput = _resolveComponent('el-input')
</script>
```
since I have read the source code, I have found that writing this way can meet my expectations, but I need to rename the resolveComponent to _ resolveComponent.

### Suggested solution

```javascript
function resolveVue3(code: string, s: MagicString) {
  const results: ResolveResult[] = []

  /**
   * when using some plugin like plugin-vue-jsx, resolveComponent will be imported as resolveComponent1 to avoid duplicate import
   */
  for (const match of code.matchAll(/_resolveComponent[0-9]*\("(.+?)"\)/g)) {
    const matchedName = match[1]
    if (match.index != null && matchedName && !matchedName.startsWith('_')) {
      const start = match.index
      const end = start + match[0].length
      results.push({
        rawName: matchedName,
        replace: resolved => s.overwrite(start, end, resolved),
      })
    }
  }

  return results
}
```

I hope this rule is Match 0 or 1 times`_`, such as `/_?resolveComponent[0-9]*\("(.+?)"\)/g`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by voyageh** [comment]
Also, it can only match component names within double quotes

**Comment by antfu** [comment]
https://github.com/unplugin/unplugin-vue-components/pull/696#issuecomment-1720829173
