### ISSUE TITLE
VScode cannot use command+click to jump to Vue3's custom component in MacOS

### ISSUE THREAD

**Issue by wjw020206** [unplugin/unplugin-vue-components#710]
### Describe the bug

For the same project, I can use ctrl+click to jump to the corresponding `.vue` file through the custom component name in Windows 10. However, I cannot use command+click to jump in MacOS. I have tried reinstalling VScode and Open other projects and the problem still exists.I use `unplugin-vue-components` to automatically import components.components.d.ts is generated.The project can run normally.

The display type is displayed when running under the windows version. However, the type of the custom component in mac displays any.TS or JS function methods and native tags such as `div` can be jumped, but custom components cannot be jumped, such as `el-button`.

Windows:
![image](https://github.com/unplugin/unplugin-vue-components/assets/59106659/79035a82-0014-463e-bd83-f14ad826942e)

MacOS:
<img width="804" alt="image" src="https://github.com/unplugin/unplugin-vue-components/assets/59106659/cd7fcd55-fe3a-4fc8-b764-d439e1c516da">

what i expected：
Use command + click on MacOS to jump to the `.vue` file of the corresponding custom component

### System Info

```Shell
- VScode version：1.84.0(arm)
- system version：MacOS Ventura 13.6
- unplugin-vue-components: 0.25.1
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wjw020206** [comment]
Please do not close this question. My project is running normally, so I cannot provide a test project. For me, I still cannot jump when I create a new project.

**Comment by wjw020206** [comment]
The problem is solved. It is a problem with the Vue Language Features (Volar) plug-in version. Version 1.8.22 has a BUG and cannot display the type of custom components. Just reduce the version to 1.8.11.

**Comment by wjw020206** [comment]
> 你能提供描述错误的问题的链接吗？

sure.
https://github.com/vuejs/language-tools/issues/3724

**Comment by Leovenn** [comment]
Yes, I also had the same problem, the problem has been solved after demotion, thank you @wjw020206
