### ISSUE TITLE
Wrong component name for folders with dash (-)

### ISSUE THREAD

**Issue by KarmaBlackshaw** [unplugin/unplugin-vue-components#738]
### Describe the bug

When nested component's parent folder has dash (-) it gives off a wrong component name.

```
RoutedMessagesIdePanel: typeof import('./src/components/routed-messages/RoutedMessagesSidePanel.vue')['default']
```

Right now, changing the parent folder to `routedMessages` works

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vtvczj?file=components.d.ts

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 12.74 GB / 31.95 GB
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by waynzh** [comment]
This is because you set `collapseSamePrefixes: true`, which collapses the same prefixes to `Ide`.
See [the definition](https://github.com/unplugin/unplugin-vue-components/blob/main/src/types.ts#L112).
