### ISSUE TITLE
Exclude comonents by filename

### ISSUE THREAD

**Issue by cirolosapio** [unplugin/unplugin-vue-components#748]
### Describe the bug

I'm trying to exclude some components by filename but they are always included in the components.d.ts file

### Reproduction

https://stackblitz.com/edit/vitejs-vite-dkyihs?file=components.d.ts&terminal=dev

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Kanade-Lu** [comment]
https://github.com/unplugin/unplugin-vue-components/issues/420
you can solve it by "globs" like
        globs: [
          '!src/components/**/excludes/*.vue', 
        ]
