### ISSUE TITLE
排除一些文件后，还是生成TS类型

### ISSUE THREAD

**Issue by Ting-Code** [unplugin/unplugin-vue-components#751]
### Describe the bug

配置了
![image](https://github.com/unplugin/unplugin-vue-components/assets/56524782/a6ab32a1-23ba-4919-88a3-fb38bcccab5b)
还是生成了Ts类型，但组件已无法使用
![image](https://github.com/unplugin/unplugin-vue-components/assets/56524782/8eefeae3-8a98-43dd-b1b5-b304347f73d4)

### Reproduction

exclude: [/once\.vue$/, /once\.vue\?vue/],

### System Info

```Shell
win10
node 18
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Kanade-Lu** [comment]
https://github.com/unplugin/unplugin-vue-components/issues/420

参考这里，使用globs解决
