### ISSUE TITLE
The primevue resolver needs to be updated for PrimeVue v4.

### ISSUE THREAD

**Issue by goldengecko** [unplugin/unplugin-vue-components#776]
### Describe the bug

src/core/resolvers/prime-vue.ts doesn't have ToggleSwitch in there. It only references InputSwitch which is the old name. There are probably other changes required to support v4

### Reproduction

add `import { PrimeVueResolver } from 'unplugin-vue-components/resolvers'` to vite.config and register it as a plugin. All the components that were in v3 are picked up fine, but ToggleSwitch was not picked up because it was renamed from InputSwitch.

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 101.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.2.0/bin/yarn
    npm: 10.8.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.126
    Safari: 17.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qcp** [comment]
I guess you need another primevue resolver.

[As doc follows](https://primevue.org/autoimport/#unplugin)
```javascript
import { PrimeVueResolver } from '@primevue/auto-import-resolver'
```

**Comment by goldengecko** [comment]
Ah, thanks for that - I have switched over and it seems to be doing the right thing.
