### ISSUE TITLE
配置了只有component下的组件自动注册，views下的组件有时候也被自动注册

### ISSUE THREAD

**Issue by qq61966100** [unplugin/unplugin-vue-components#795]
### Describe the bug

Hi, 我的配置如下
`Components({
      // 生成自定义 `auto-components.d.ts` 全局声明
      dts: 'src/types/auto-components.d.ts',
      // 自定义组件的解析器
      resolvers: [ElementPlusResolver()],
      globs: [
        'src/components/**/**.{vue, md}',
        '!src/components/DiyEditor/components/mobile/**',
        '!public/excel/**'
      ]
    }),`
并没有配置views下的vue组件，但是有时候，views下的组件会被自动注册进去，有时候又不注册，想问下，这是为什么？

### Reproduction

有时候有，有时候没有

### System Info

```Shell
windows11, vscode
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Kanade-Lu** [comment]
你的版本是？有相似的问题在上个版本已经被修复了，可以更新到最新版本测试一下

**Comment by qq61966100** [comment]
好的，多谢
